# Generated by Django 5.1.6 on 2025-03-23 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0002_wificredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('additional_details', models.TextField()),
            ],
        ),
    ]
