# Generated by Django 5.1.6 on 2025-03-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0003_specialguest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialguest',
            name='image_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='specialguest',
            name='pin_code',
            field=models.CharField(max_length=255),
        ),
    ]
