# Generated by Django 5.1.6 on 2025-03-25 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0004_alter_specialguest_image_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryFailureNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
