# Generated by Django 5.1.6 on 2025-03-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0005_entryfailurenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryfailurenotification',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
