# Generated by Django 5.1.6 on 2025-03-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0007_entryfailurenotification_savedpin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryfailurenotification',
            name='savedPin',
        ),
        migrations.AddField(
            model_name='entryfailurenotification',
            name='phoneNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='entryfailurenotification',
            name='savedPinCode',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
