# Generated by Django 5.1.6 on 2025-03-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0008_remove_entryfailurenotification_savedpin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_details', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='entryfailurenotification',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='entryfailurenotification',
            name='savedPinCode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
