# Generated by Django 5.1.6 on 2025-03-31 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0009_cameradata_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntryFailureNotification',
            new_name='ViewRequest',
        ),
    ]
