# Generated by Django 5.1.6 on 2025-03-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0011_emergency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='emergency',
            name='date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='emergency',
            name='time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
