# Generated by Django 5.1.6 on 2025-04-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0013_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewrequest',
            name='CAMImageID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='viewrequest',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='viewrequest',
            name='savedPinCode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
