# Generated by Django 5.1.6 on 2025-04-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0014_viewrequest_camimageid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulUnsuccessfulEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('case', models.CharField(max_length=50)),
                ('camera_image_id', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
