# Generated by Django 5.1.6 on 2025-04-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0015_successfulunsuccessfulentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='successfulunsuccessfulentry',
            name='message',
            field=models.CharField(default='', max_length=200),
        ),
    ]
