# Generated by Django 5.1.6 on 2025-04-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0017_onetimeguestentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimeguestentry',
            name='image_ip',
        ),
        migrations.AddField(
            model_name='onetimeguestentry',
            name='image',
            field=models.ImageField(default='', upload_to='one_time_guests/'),
            preserve_default=False,
        ),
    ]
