# Generated by Django 5.1.6 on 2025-04-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0018_remove_onetimeguestentry_image_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='fingerprint_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
