# Generated by Django 5.1.6 on 2025-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0019_alter_owner_fingerprint_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultPinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pin_code', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='LocationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('google_maps_link', models.TextField()),
                ('written_location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
