# Generated by Django 5.1.6 on 2025-04-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartdoor', '0020_defaultpincode_locationentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultpincode',
            name='pin_code',
            field=models.CharField(max_length=6),
        ),
    ]
